import type { Voice } from '@/types'

export const PREDEFINED_VOICES: Voice[] = [
  {
    id: 'alba',
    name: 'Alba',
    language: 'English',
    description: 'Natural, warm female voice',
    hfUrl: 'hf://kyutai/tts-voices/alba-mackenna/casual.wav',
    gender: 'female',
  },
  {
    id: 'anna',
    name: 'Anna',
    language: 'English',
    description: 'Clear, professional female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p228_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'vera',
    name: 'Vera',
    language: 'English',
    description: 'Expressive female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p229_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'fantine',
    name: 'Fantine',
    language: 'English',
    description: 'Soft, melodic female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p244_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'eponine',
    name: 'Eponine',
    language: 'English',
    description: 'Bright, energetic female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p262_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'azelma',
    name: 'Azelma',
    language: 'English',
    description: 'Gentle, articulate female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p303_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'mary',
    name: 'Mary',
    language: 'English',
    description: 'Calm, measured female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p333_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'jane',
    name: 'Jane',
    language: 'English',
    description: 'Confident, clear female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p339_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'eve',
    name: 'Eve',
    language: 'English',
    description: 'Rich, resonant female voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p361_023_enhanced.wav',
    gender: 'female',
  },
  {
    id: 'cosette',
    name: 'Cosette',
    language: 'English',
    description: 'Expressive, emotive female voice',
    hfUrl: 'hf://kyutai/tts-voices/expresso/ex04-ex02_confused_001_channel1_499s.wav',
    gender: 'female',
  },
  {
    id: 'caro_davy',
    name: 'Caro Davy',
    language: 'English',
    description: 'Natural, conversational female voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-zero/caro_davy.wav',
    gender: 'female',
  },
  {
    id: 'charles',
    name: 'Charles',
    language: 'English',
    description: 'Distinguished, authoritative male voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p254_023_enhanced.wav',
    gender: 'male',
  },
  {
    id: 'paul',
    name: 'Paul',
    language: 'English',
    description: 'Steady, reliable male voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p259_023_enhanced.wav',
    gender: 'male',
  },
  {
    id: 'george',
    name: 'George',
    language: 'English',
    description: 'Deep, resonant male voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p315_023_enhanced.wav',
    gender: 'male',
  },
  {
    id: 'michael',
    name: 'Michael',
    language: 'English',
    description: 'Clear, professional male voice',
    hfUrl: 'hf://kyutai/tts-voices/vctk/p360_023_enhanced.wav',
    gender: 'male',
  },
  {
    id: 'jean',
    name: 'Jean',
    language: 'English',
    description: 'Warm, expressive male voice',
    hfUrl: 'hf://kyutai/tts-voices/ears/p010/freeform_speech_01_enhanced.wav',
    gender: 'male',
  },
  {
    id: 'marius',
    name: 'Marius',
    language: 'English',
    description: 'Energetic, youthful male voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-donations/Selfie.wav',
    gender: 'male',
  },
  {
    id: 'javert',
    name: 'Javert',
    language: 'English',
    description: 'Strong, commanding male voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-donations/Butter.wav',
    gender: 'male',
  },
  {
    id: 'bill_boerst',
    name: 'Bill Boerst',
    language: 'English',
    description: 'Mature, authoritative male voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-zero/bill_boerst.wav',
    gender: 'male',
  },
  {
    id: 'peter_yearsley',
    name: 'Peter Yearsley',
    language: 'English',
    description: 'Crisp, articulate male voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-zero/peter_yearsley.wav',
    gender: 'male',
  },
  {
    id: 'stuart_bell',
    name: 'Stuart Bell',
    language: 'English',
    description: 'Smooth, broadcast-quality male voice',
    hfUrl: 'hf://kyutai/tts-voices/voice-zero/stuart_bell.wav',
    gender: 'male',
  },
  {
    id: 'estelle',
    name: 'Estelle',
    language: 'French',
    description: 'Elegant French female voice',
    hfUrl: 'hf://kyutai/tts-voices/unmute-prod-website/developpeuse-3.wav',
    gender: 'female',
  },
  {
    id: 'giovanni',
    name: 'Giovanni',
    language: 'Italian',
    description: 'Warm Italian male voice',
    hfUrl: 'hf://kyutai/pocket-tts/common_voice_it_36520747-enhanced-v2.mp3',
    gender: 'male',
  },
  {
    id: 'lola',
    name: 'Lola',
    language: 'Spanish',
    description: 'Vibrant Spanish female voice',
    hfUrl: 'hf://kyutai/pocket-tts/common_voice_es_19762977-enhanced-v2.mp3',
    gender: 'female',
  },
  {
    id: 'juergen',
    name: 'Juergen',
    language: 'German',
    description: 'Clear German male voice',
    hfUrl: 'hf://kyutai/pocket-tts/de-DE-juergen.mp3',
    gender: 'male',
  },
  {
    id: 'rafael',
    name: 'Rafael',
    language: 'Portuguese',
    description: 'Expressive Portuguese male voice',
    hfUrl: 'hf://kyutai/pocket-tts/g-Vi8PgmSY0-enhanced-v2.wav',
    gender: 'male',
  },
]

export const LANGUAGES = [
  { id: 'english', label: 'English', flag: '🇬🇧' },
  { id: 'english_2026-01', label: 'English (2026-01)', flag: '🇬🇧' },
  { id: 'english_2026-04', label: 'English (2026-04)', flag: '🇬🇧' },
  { id: 'french_24l', label: 'French', flag: '🇫🇷' },
  { id: 'german_24l', label: 'German', flag: '🇩🇪' },
  { id: 'portuguese_24l', label: 'Portuguese', flag: '🇵🇹' },
  { id: 'italian_24l', label: 'Italian', flag: '🇮🇹' },
  { id: 'spanish_24l', label: 'Spanish', flag: '🇪🇸' },
] as const

export const DEFAULT_VOICE_FOR_LANGUAGE: Record<string, string> = {
  italian: 'giovanni',
  spanish: 'lola',
  german: 'juergen',
  portuguese: 'rafael',
  french: 'estelle',
}

export const getDefaultVoice = (language: string): Voice => {
  const defaultId = Object.entries(DEFAULT_VOICE_FOR_LANGUAGE).find(([key]) =>
    language.includes(key)
  )?.[1] ?? 'alba'
  return PREDEFINED_VOICES.find((v) => v.id === defaultId) ?? PREDEFINED_VOICES[0]
}

export const getVoiceById = (id: string): Voice | undefined =>
  PREDEFINED_VOICES.find((v) => v.id === id)
